EXTENSION = password_validation
MODULE_big = password_validation
DATA = password_validation--0.0.1.sql
OBJS = password_validation.o
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

