EXTENSION = password-validation
MODULE_big = password-validation
DATA = password-validation--0.0.1.sql
OBJS = password-validation.o
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

